services:
  - type: web
    name: crypto-news-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class uvicorn.workers.UvicornWorker bot:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CRYPTOCOMPARE_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false 