services:
  - type: web
    name: crypto-news-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CRYPTOCOMPARE_API_KEY
        sync: false 